import type { Metadata } from "next";
import { MantineProvider, ColorSchemeScript, mantineHtmlProps } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.scss";
import { HeaderSimple } from "./components/Header"; // Ensure Header is imported

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <HeaderSimple /> {/* ✅ Ensure header is placed outside <main> */}
          <main>{children}</main>
        </MantineProvider>
      </body>
    </html>
  );
}
